---

- set_fact:
    pool_list="{{ vip_pool.split('#')}}"
  
    
- block:
    - debug: var=vip_ip
    - debug: var=vip_port
    - debug: var=vip_cert
    - debug: var=vip_cert_key
    - debug: var=vip_pool
    - debug: var=vip_desc
    - debug: var=pool_list
    - debug: var=create_pool
    - debug: var=vip_irules
    - debug: var=vip_persist
    - debug: var=vip_persist_profile
    - debug: var=ssl_parent

- name: Build JSON payload
  template: src="iapp.j2" dest="files/iapp.json"

- name: Deploy F5 iApp 
  bigip_iapp_service:
    name: "{{ iapp_service_name }}"
    template: FirstBank.v1.5
    server: "{{ f5_host }}"
    user: "{{ f5_user }}"
    password: "{{ f5_password }}"
    parameters: "{{ lookup('file', 'iapp.json')| from_json }}"
    validate_certs: false
    #traffic_group: "{{ traffic_group }}"
    state: present
